//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbGamingEntities : DbContext
    {
        public dbGamingEntities()
            : base("name=dbGamingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<data_Affix> data_Affix { get; set; }
        public virtual DbSet<data_Material> data_Material { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Player_Affix> Player_Affix { get; set; }
        public virtual DbSet<Player_Material> Player_Material { get; set; }
    }
}
